export const ROUTE_PATHS = {
  home: '/',
  components: '/components',
  following: '/following',
  ditan: '/ditan',
  publish: '/publish',
  profile: '/profile',
  search: '/search',
  noteDetail: (noteId = ':id') => `/note/${noteId}`,
  storeDetail: (storeId = ':id') => `/store/${storeId}`,
  legacyShopDetail: (shopId = ':shopId') => `/shops/${shopId}`,
  legacyNoteDetail: (noteId = ':noteId') => `/notes/${noteId}`,
  userProfile: (userId = ':userId') => `/users/${userId}`,
  my: '/me',
  login: '/auth/login',
} as const;
