export const ROUTE_PATHS = {
  home: '/',
  preview: '/preview',
  components: '/components',
  following: '/following',
  ditan: '/ditan',
  publish: '/publish',
  my: '/me',
  legacyProfile: '/profile',
  search: '/search',
  noteDetail: (noteId = ':noteId') => `/notes/${noteId}`,
  legacyNoteDetail: (noteId = ':id') => `/note/${noteId}`,
  shopDetail: (shopId = ':shopId') => `/shops/${shopId}`,
  legacyShopDetail: (shopId = ':id') => `/store/${shopId}`,
  userProfile: (userId = ':userId') => `/users/${userId}`,
  login: '/auth/login',
} as const;
